kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000 # Argo Server NodePort
    hostPort: 2746        # Access via https://localhost:2746
    listenAddress: "0.0.0.0"
    protocol: TCP